apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginxProxy.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nginxProxy.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginxProxy.name }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginxProxy.image }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: {{ .Values.nginxProxy.port }}
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
