apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        error_log /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;

        # Upstream 配置
        upstream app_a {
            server app-a.default.svc.cluster.local:8080 max_fails=3 fail_timeout=5s;
            least_conn;
            check interval=5000 rise=2 fall=3 timeout=2000 type=http;
            check_http_send "GET /actuator/health HTTP/1.1\r\nHost: app-a\r\nConnection: close\r\n\r\n";
            check_http_expect_alive http_2xx http_3xx;
        }

        upstream app_b {
            server app-b.default.svc.cluster.local:8080 max_fails=3 fail_timeout=5s;
            check interval=5000 rise=2 fall=3 timeout=2000 type=http;
            check_http_send "GET /actuator/health HTTP/1.1\r\nHost: app-b\r\nConnection: close\r\n\r\n";
            check_http_expect_alive http_2xx http_3xx;
        }

        # 目標 2：針對特定 URL（不同域名）分流
        server {
            listen 80;
            server_name app-a.mychart3.local;
            location / {
                proxy_pass http://app_a;
                proxy_set_header Host $host;
            }
            error_page 502 =503 /fallback;
            location /fallback {
                return 503 "Service Temporarily Unavailable";
            }
        }

        server {
            listen 80;
            server_name app-b.mychart3.local;
            location / {
                proxy_pass http://app_b;
                proxy_set_header Host $host;
            }
            error_page 502 =503 /fallback;
            location /fallback {
                return 503 "Service Temporarily Unavailable";
            }
        }

        # 目標 1：URL 分流
        server {
            listen 80;
            server_name mychart3.local;

            location /a {
                proxy_pass http://app_a/actuator/health;
                proxy_set_header Host $host;
            }

            location /b {
                proxy_pass http://app_b/actuator/health;
                proxy_set_header Host $host;
            }

            # 修正 /special?type=a 或 type=b 轉發問題
            location /special {
                set $target "http://app_a/actuator/health";
                if ($arg_type = "b") {
                    set $target "http://app_b/actuator/health";
                }
                proxy_pass $target;
                proxy_set_header Host $host;
            }

            # 修正 /dynamic 根據 Header 轉發
            set $upstream "http://app_a/actuator/health";
            location /dynamic {
                if ($http_x_app_type = "app-b") {
                    set $upstream "http://app_b/actuator/health";
                }
                proxy_pass $upstream;
                proxy_set_header Host $host;
            }

            # 修正 /status，避免 500 錯誤
            location /status {
                return 200 "NGINX Proxy is running";
            }

            # 默認回應
            location / {
                return 200 "NGINX Proxy is running";
            }

            error_page 502 =503 /fallback;
            location /fallback {
                return 503 "Service Temporarily Unavailable";
            }
        }
    }