apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/YanYi-Li/helm.git
  ref:
    branch: main
