apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myapp2
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: mychart2
      sourceRef:
        kind: GitRepository
        name: helm
        namespace: flux-system
  values:
    ingress:
      enabled: false
