apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myapp
  namespace: default
spec:
  interval: 1m  # 每分鐘檢查一次是否有變更
  chart:
    spec:
      chart: ./mychart  # 這要對應你的 Helm Chart 目錄
      sourceRef:
        kind: GitRepository
        name: helm
        namespace: flux-system
  values:
    replicaCount: 3
    image:
      repository: nginx
      tag: latest
    service:
      type: ClusterIP
      port: 80
