replicaCount: 3

image:
  repository: zxc25321716/spring-boot-demo  # 你的 Docker Hub Repository
  tag: v1
  pullPolicy: IfNotPresent

service:
  name: myapp2  # 確保這裡的名稱和 Service 一致
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true

ingress:
  enabled: true 
  className: "nginx"
  hosts:
    - host: "myapp2local"
      paths:
        - path: /
          pathType: Prefix	
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /	

autoscaling:
  enabled: false  
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

