replicaCount: 2  

image:
  repository: zxc25321716/spring-boot-demo  # 你的 Docker Hub Repository
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true

ingress:
  enabled: false
  hosts:
    - host: "myapp.local"  
      paths:
        - path: /
          pathType: Prefix	

autoscaling:
  enabled: false  
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

